name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Angular Build and push image 
        uses: docker/build-push-action@v5
        with:
          context: thanedar-ui
          file: thanedar-ui/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/thanedar-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/thanedar-ui:${{ github.sha }}
      - name: Django Build and push image
        uses: docker/build-push-action@v5
        with:
          context: thanedarbe
          file: thanedarbe/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/thanedarbe:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/thanedarbe:${{ github.sha }}